export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const CREATE_QUESTION_FAIL = "CREATE_QUESTION_FAIL";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const GET_BODY = "GET_BODY";
export const UPDATE_QUESTION = "UPDATE_QUESTION";

export const GET_QUESTIONS = "GET_QUESTIONS";
